# Generated by Django 3.0.6 on 2020-05-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_blogcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
