# Generated by Django 3.0.6 on 2020-05-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200530_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogcontentSingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogcontent_id', models.IntegerField()),
                ('title_name', models.CharField(max_length=50)),
            ],
        ),
    ]
