# Generated by Django 3.0.6 on 2020-05-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200530_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcontentsingle',
            old_name='blogcontent_id',
            new_name='blog_id',
        ),
    ]
