# Generated by Django 3.0.6 on 2020-05-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200530_2119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogcontentSingle',
            new_name='Blogcontent_Single',
        ),
        migrations.AddField(
            model_name='blogcontent',
            name='bodys',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
