# Generated by Django 3.0.6 on 2020-05-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200530_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcontent',
            name='bodys',
        ),
    ]
