# Generated by Django 3.0.6 on 2020-05-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_blogcontent_bodys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogcontent',
        ),
    ]
