# Generated by Django 3.0.6 on 2020-05-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_delete_blogcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent_single',
            name='title_name',
            field=models.CharField(max_length=101),
        ),
    ]
