# Generated by Django 3.0.6 on 2020-05-30 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200530_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent_single',
            name='title_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Blogcontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('blogcontent_Single', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Blogcontent_Single')),
            ],
        ),
    ]
