# Generated by Django 3.0.6 on 2020-05-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20200530_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='blogcontent_single',
            name='title_name',
            field=models.CharField(max_length=300),
        ),
    ]
