# Generated by Django 3.0.6 on 2020-07-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20200707_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_use',
            field=models.DateField(blank=True),
        ),
    ]
