# Generated by Django 3.0.6 on 2020-07-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20200708_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_use',
            field=models.DateTimeField(blank=True),
        ),
    ]
