# Generated by Django 3.0.6 on 2020-07-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_city_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='district',
            name='district_id',
        ),
    ]
