# Generated by Django 3.0.6 on 2020-07-29 15:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20200727_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='body_content',
            field=models.TextField(default=datetime.datetime(2020, 7, 29, 15, 28, 50, 18488, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcontent',
            name='body_text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcontent',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
