# Generated by Django 3.0.6 on 2020-07-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20200729_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcontent',
            old_name='image2',
            new_name='image_text',
        ),
    ]
