# Generated by Django 3.0.6 on 2020-08-02 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20200729_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='about_city',
        ),
        migrations.RemoveField(
            model_name='district',
            name='about_district',
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default='True', max_length=10),
        ),
        migrations.CreateModel(
            name='ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.district')),
            ],
        ),
    ]
