# Generated by Django 3.0.6 on 2020-08-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20200802_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pack',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
