# Generated by Django 3.0.6 on 2020-08-02 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20200802_1437'),
        ('user', '0003_auto_20200727_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ward',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='home.ward'),
        ),
    ]
