# Generated by Django 3.0.6 on 2020-06-10 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20200530_2154'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Product')),
                ('sCart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.ShopCart')),
            ],
        ),
    ]
