# Generated by Django 3.0.6 on 2020-07-08 16:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_orderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 16, 42, 46, 946591, tzinfo=utc)),
        ),
    ]
