# Generated by Django 3.0.6 on 2020-07-10 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200710_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 13, 54, 0, 101986, tzinfo=utc)),
        ),
    ]
