# Generated by Django 3.0.6 on 2020-07-11 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20200710_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 14, 0, 35, 749995, tzinfo=utc)),
        ),
    ]
