# Generated by Django 3.0.6 on 2020-07-27 08:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20200727_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 8, 8, 43, 730196, tzinfo=utc)),
        ),
    ]
