# Generated by Django 3.0.6 on 2020-07-29 15:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20200727_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 15, 28, 26, 325736, tzinfo=utc)),
        ),
    ]
