# Generated by Django 3.0.6 on 2020-07-29 16:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20200729_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 16, 18, 9, 572647, tzinfo=utc)),
        ),
    ]
