# Generated by Django 3.0.6 on 2020-08-02 08:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20200802_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 8, 9, 6, 731743, tzinfo=utc)),
        ),
    ]
