# Generated by Django 3.0.6 on 2020-08-02 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20200802_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 12, 56, 42, 652321, tzinfo=utc)),
        ),
    ]
