# Generated by Django 3.0.6 on 2020-08-02 13:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20200802_1437'),
        ('order', '0023_auto_20200802_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.ward'),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 13, 1, 53, 523436, tzinfo=utc)),
        ),
    ]
