# Generated by Django 3.0.6 on 2020-08-04 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_auto_20200804_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 11, 47, 9, 943521, tzinfo=utc)),
        ),
    ]
