# Generated by Django 3.0.6 on 2020-08-06 08:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_auto_20200804_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 8, 12, 48, 839066, tzinfo=utc)),
        ),
    ]
