# Generated by Django 3.0.6 on 2020-08-09 03:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_auto_20200809_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 3, 21, 3, 305531, tzinfo=utc)),
        ),
    ]
