# Generated by Django 3.0.6 on 2020-08-10 05:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0049_auto_20200809_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Shipper'),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 5, 1, 17, 519799, tzinfo=utc)),
        ),
    ]
